### ISSUE TITLE
Output via pipe

### ISSUE THREAD

**Issue by andreas-ibm** [vgropp/bwm-ng#24] opened 2019-09-03 14:19 UTC
When I run bwm-ng, e.g. like so:
`bwm-ng -I ens9 -u bits -o csv -t 1000 | cat`
The output is buffered massively, if I pass it through script or stdbuf I get the output straight away:
`script -q -f -c "bwm-ng -I ens9 -u bits -o csv -t 1000" | cat`
or:
`stdbuf -oL -eL bwm-ng -I ens9 -u bits -o csv -t 1000 | cat`

I know it's a non-trivial fix, but could you either
a) fix it 
b) document the workaround so others can find it easily!

Obviously I'm not using cat but another program to analyze the csv output (and removing the total lines)...

**Comment by vgropp** [comment] 2019-09-06 11:48
Hi,

i cannot reproduce it on my system. CSV output is already flushed after each iteration. What is your OS/distribution?

**Comment by andreas-ibm** [comment] 2019-09-06 12:00
Interesting!
$lsb_release -a
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
$uname -a
```
Linux dre-thinkpad 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
$ulimit -a
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62391
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 15000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 62391
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by Kurtas** [comment] 2019-09-23 16:16
@andreas-ibm Thanks a lot, I had the same issue when I tried to spawn node process with `bwm-ng` and your solution with `stdbuf` works!

@vgropp Maybe hint for you what's going on will be here https://stackoverflow.com/questions/43397426/spawned-child-process-stdout-to-readline-without-buffering-in-node

**Comment by vgropp** [comment] 2019-09-23 16:32
The fix (as mentioned in the stackoverflow link by @Kurtas) is already in current bwm-ng via #9. I guess you both are using the package from bionic (https://packages.ubuntu.com/bionic/bwm-ng) or debian stable. You can ask the maintainer to backport the fix, use a different package (debian sid/testing) or compile it yourself.

I close this issue as i think it is fixed, else please comment again.

**Closed by vgropp** 2019-09-23 16:32 UTC

**Comment by Kurtas** [comment] 2019-09-24 06:33
@vgropp Confirming, I just compiled 0.6.2 and it's really fixed. Thanks

**Comment by andreas-ibm** [comment] 2019-09-24 07:50
Thanks, cant believe the package is so old!
